### ISSUE TITLE
Conflict with NodeJS plugin in Jenkins Build Environment

### ISSUE THREAD

**Issue by sigian80** [codevise/jenkins-mysql-job-databases-plugin#2]
Hello,

I have a problem with simultaneous use of MySQL Job Database Plugin (0.1.0) and NodeJS Plugin (0.2.1) in the "Build Environment" definition of a Jenkins job.

The environment, where job runs, is a Jenkins master (core version:1.565) on Ubuntu 12.04 with a MySQL installation (5.5.3) and NodeJS installation is 0.10.x (I also used a 0.11.x).

Below there is the log of the build that fails for a "bash: mysql: command not found" error. If Jenkins doesn't find a NodeJS installation, it tries to perform a NodeJS installation and then uses MySQL Job Database plugin to create a mysql database. The issue could be about the path that MySQL Job Database uses to run bash commands, maybe it could be modified by NodeJS Plugin before. Obviously, without the use of NodeJS plugin, MySQL Job Database Plugin works correctly.

Looking for your feedback, thank you in advance,
Silvio

Building on master in workspace /var/lib/jenkins/jobs/Testmysql-clone/workspace
Updating http://163.162.63.177/myproject/trunk/project at revision '2015-02-10T15:52:58.795 +0100'
At revision 2289
no change for http://163.162.63.177/myproject/trunk/project since the previous build
Ensuring MySQL database for job exists
$ bash -c 'mysql --host='127.0.0.1' --port='3306' --user='jenkins' --password='jenkins' --execute "CREATE DATABASE IF NOT EXISTS test;"'
MySQL command failed:

bash: mysql: command not found

ERROR: null
[htmlpublisher] Archiving HTML reports...
[htmlpublisher] Archiving at PROJECT level /var/lib/jenkins/jobs/Testmysql-clone/workspace/project/coverage/lcov-report to /var/lib/jenkins/jobs/Testmysql-clone/htmlreports/Code_Coverage_analysis
ERROR: Specified HTML directory '/var/lib/jenkins/jobs/Testmysql-clone/workspace/project/coverage/lcov-report' does not exist.
Drop MySQL database for job if exists
$ bash -c 'mysql --host='127.0.0.1' --port='3306' --user='jenkins' --password='jenkins' --execute "DROP DATABASE IF EXISTS test;"'
MySQL command failed:

bash: mysql: command not found

Drop MySQL user for job if exists
$ bash -c 'mysql --host='127.0.0.1' --port='3306' --user='jenkins' --password='jenkins' --execute "REVOKE ALL PRIVILEGES, GRANT OPTION FROM 'jenkinsuser'@'%';"'
MySQL command failed:

bash: mysql: command not found

Finished: FAILURE

**Comment by tf** [comment]
Hi Silvio,

this plugin expects `mysql` to be on the path. So I guess the NodeJS manipulates the `$PATH` in a way, such that `mysql` is no longer available. Maybe try building a job with a script section that simply echos `$PATH` and outputs `which mysql`. Enabling/disabling the NodeJS plugin should reveal the difference. Still, I think this has to fixed or configured correctly in the NodeJS plugin. This plugin simply depends on the executable to be available.

Cheers
Tim
