### ISSUE TITLE
bash: mysql: command not found

### ISSUE THREAD

**Issue by tonylegrone** [codevise/jenkins-mysql-job-databases-plugin#4]
It appears that this plugin doesn't set the $PATH defined in the jenkins global config and assumes the mysql binary is located in /usr/bin. I was having issues because I installed mysql on my build server with homebrew.

It would be helpful is this plugin user the the $PATH set by jenkins or allowed users to provide an alternative path to mysql in it's own config.

I could probably work on a patch to add a config field to set a custom path to mysql since the looks pretty easy in the plugin's code, but I wouldn't know where to begin on loading the $PATH from jenkins.

**Comment by tf** [comment]
We already [set environment variables](https://github.com/codevise/jenkins-mysql-job-databases-plugin/blob/master/models/mysql_builder.rb#L44) in the `MysqlBuilder`. Maybe one could check whether a `$PATH` variable already exists there?

We also already [read from the global configuration](https://github.com/codevise/jenkins-mysql-job-databases-plugin/blob/master/models/mysql_builder.rb#L70) - but only options that we defined ourselves.

As an alternative, we could consider adding a global config option which allows specifying an absolute path to the `mysql` executable which is [used to run commands](https://github.com/codevise/jenkins-mysql-job-databases-plugin/blob/master/models/mysql.rb#L26). Honoring the configured `$PATH` seems cleaner, though.

@n-rodriguez Any idea how this could be done?

**Comment by n-rodriguez** [comment]
@tf @tonylegrone : Switch to [jbox-web/job-database-manager-mysql](https://github.com/jbox-web/job-database-manager-mysql)
